name: Update Contributors

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Retrieve contributors and update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          curl -s -H "Authorization: token ${GH_TOKEN}" "https://api.github.com/repos/${REPO}/contributors" > contributors.json
          
          CONTRIBUTORS_HTML=$(jq -r '.[] | 
            "<a href=\"" + .html_url + "\" title=\"" + (.login | @html) + "\" target=\"_blank\">" +
            "<img src=\"" + .avatar_url + "&s=100\" width=\"100px\" alt=\"" + (.login | @html) + "\" " +
            "style=\"border-radius: 50%; margin: 0 5px;\" /></a>"' contributors.json | paste -sd " " -)
          
          NEW_SECTION=$(printf "<!-- CONTRIBUTORS:START -->\n\n%s\n\n<!-- CONTRIBUTORS:END -->" "$CONTRIBUTORS_HTML")
          
          ESCAPED_CONTENT=$(printf '%s' "$NEW_SECTION" | sed -e 's/[\/&]/\\&/g')
          
          perl -0777 -pi -e "s/<!-- CONTRIBUTORS:START -->.*?<!-- CONTRIBUTORS:END -->/${ESCAPED_CONTENT}/s" README.md

      - name: Commit updated README
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update contributors list [skip ci]"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
